from Bio.Seq import Seq


a='GCAGCACCTGTCTCACGGTTCCCGAAGGCACATTCTCATCTCTGAAAACTTCCGTGGATGTCAAGACCAGGTAAGGTTCTTCGC'[::-1]
b='GCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGGTGCTGC'
print(len(a))
a=Seq(a)
b=Seq(b)
print(a.complement()==b)